# Generated by Django 6.0.2 on 2026-06-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brand_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='desc_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='shadow_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='title_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
