# Generated by Django 6.0.2 on 2026-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_blog_slug_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='slideshows/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
