# Generated by Django 6.0.2 on 2026-05-06 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ឈ្មោះប្រភេទ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='មិនទាន់ដាក់ឈ្មោះ', max_length=255, verbose_name='ឈ្មោះផលិតផល'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideshow',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='បង្ហាញលើ Web'),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='ចំណងជើងរង'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='ខ្លឹមសារ'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog_images/', verbose_name='រូបភាព'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ចំណងជើងអត្ថបទ'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ឈ្មោះម៉ាក'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ការពិពណ៌នា'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='រូបភាពចម្បង'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='តម្លៃ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='ចំនួនក្នុងស្តុក'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='image',
            field=models.ImageField(upload_to='slideshows/', verbose_name='រូបភាព'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='តំណភ្ជាប់ (URL)'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ចំណងជើង'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.category'),
        ),
    ]
