# Generated by Django 6.0.2 on 2026-05-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='តម្លៃដើម (តម្លៃមុនបញ្ចុះ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.TextField(blank=True, help_text='ឧទាហរណ៍៖ Free Standy Free Bottle...', null=True, verbose_name='ព័ត៌មានបន្ថែម/Promotion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='តម្លៃបច្ចុប្បន្ន'),
        ),
    ]
