# Generated by Django 6.0.2 on 2026-05-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_product_old_price_product_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='នាមខ្លួន')),
                ('last_name', models.CharField(max_length=100, verbose_name='គោត្តនាម')),
                ('city', models.CharField(max_length=100, verbose_name='ខេត្ត/ក្រុង')),
                ('address_1', models.CharField(max_length=255, verbose_name='អាសយដ្ឋានបច្ចុប្បន្ន')),
                ('address_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='ព័ត៌មានបន្ថែមសម្គាល់ទីតាំង')),
                ('phone', models.CharField(max_length=20, verbose_name='លេខទូរស័ព្ទ')),
                ('email', models.EmailField(max_length=254, verbose_name='អ៊ីមែល')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='ចំណាំបន្ថែមលើការបញ្ជាទិញ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ទឹកប្រាក់សរុប')),
                ('payment_method', models.CharField(choices=[('cod', 'បង់ប្រាក់ពេលទំនិញទៅដល់ (COD)'), ('online', 'ទូទាត់តាមកាត ឬ KHQR')], default='cod', max_length=20, verbose_name='វិធីសាស្ត្រទូទាត់')),
                ('status', models.CharField(choices=[('Pending', 'រង់ចាំពិនិត្យ'), ('Processing', 'កំពុងរៀបចំ'), ('Shipped', 'កំពុងដឹកជញ្ជូន'), ('Completed', 'ជោគជ័យ'), ('Cancelled', 'បានបោះបង់')], default='Pending', max_length=20, verbose_name='ស្ថានភាពកុម្ម៉ង់')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបញ្ជាទិញ')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='ចំនួន')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='តម្លៃពេលទិញ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.order', verbose_name='ការបញ្ជាទិញ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product', verbose_name='ផលិតផល')),
            ],
        ),
    ]
