# Generated by Django 6.0.2 on 2026-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
