# Generated by Django 6.0.2 on 2026-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_slideshow_description_slideshow_link_slideshow_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='desc_color',
            field=models.CharField(default='#e0e0e0', max_length=10),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='shadow_color',
            field=models.CharField(default='rgba(0,0,0,0.5)', max_length=10),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='title_color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
