# Generated by Django 6.0.2 on 2026-07-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='PNK MOBILE STORE', max_length=255)),
                ('phone', models.CharField(default='096 29 647 13', max_length=50)),
                ('email', models.EmailField(default='dana267yue@gmail.com', max_length=254)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('address', models.CharField(default='ភូមិនិគមន៍លើ ខេត្តត្បូងឃ្មុំ, ព្រះរាជាណាចក្រកម្ពុជា', max_length=500)),
                ('facebook_link', models.URLField(blank=True, default='https://facebook.com/pnkmobile', max_length=500, null=True)),
                ('telegram_link', models.URLField(blank=True, default='https://t.me/pnkmobile', max_length=500, null=True)),
            ],
        ),
    ]
