# Generated by Django 6.0.2 on 2026-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_storesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='map_iframe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
