# Generated by Django 6.0.2 on 2026-08-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_storesetting_store_name_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='chat_auto_reply',
            field=models.TextField(blank=True, default='សូមអរគុណសម្រាប់ការផ្ញើសារ! ក្រុមការងារ PNK SHOP បានទទួលសាររបស់អ្នកហើយ។ លោកអ្នកក៏អាចឆាតផ្ទាល់តាម Telegram:', null=True),
        ),
    ]
