# Generated by Django 6.0.2 on 2026-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_storesetting_chat_auto_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='enable_auto_reply',
            field=models.BooleanField(default=True),
        ),
    ]
