# Generated by Django 6.0.2 on 2026-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_storesetting_enable_auto_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_hours_a',
            field=models.TextField(blank=True, default='ហាង <strong>PNK SHOP</strong> បើកបម្រើអតិថិជនរៀងរាល់ថ្ងៃ ពីម៉ោង <strong>7:30 ព្រឹក ដល់ 8:30 យប់</strong>! អាចអញ្ជើញមកផ្ទាល់ ឬកុម្មង់តាមអនឡាញបានរហ័ស។ 🕒', null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_hours_q',
            field=models.CharField(blank=True, default='🕒 តើហាងបើកលក់ម៉ោងប៉ុន្មាន?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_installment_a',
            field=models.TextField(blank=True, default='💳 <strong>សេវាកម្ម បង់រំលស់ងាយៗ</strong>៖<br>• ការប្រាក់ចាប់ពី 0% ដល់ 5% ឯកសារងាយៗ<br>• អនុម័តរហ័សក្នុងរយៈពេល ១៥-៣០ នាទី<br>• ឯកសារ៖ អត្តសញ្ញាណប័ណ្ណ + សៀវភៅគ្រួសារ/ស្នាក់នៅ + លិខិតបញ្ជាក់ប្រាក់ខែ<br>👉 សូមផ្ញើ <strong>ម៉ូឌែលទូរស័ព្ទដែលចង់បាន</strong> មកកាន់ទីនេះដើម្បីឱ្យ Admin ជួយគណនាប្រាក់បង់ប្រចាំខែជូនបាទ/ចាស! 📱✨', null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_installment_q',
            field=models.CharField(blank=True, default='💳 សួរអំពីការបង់រំលស់ 5%?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_shipping_a',
            field=models.TextField(blank=True, default='យើងខ្ញុំមានសេវាដឹកជញ្ជូនរហ័សទាន់ចិត្ត និងសុវត្ថិភាព ដល់ដៃអតិថិជននៅគ្រប់ <strong>២៤ ខេត្តក្រុង</strong> ទូទាំងប្រទេសកម្ពុជា! 📦🚚', null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_shipping_q',
            field=models.CharField(blank=True, default='🚚 តើមានសេវាដឹកជញ្ជូន ២៤ ខេត្តក្រុងទេ?', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_tradein_a',
            field=models.TextField(blank=True, default='🔄 <strong>សេវាកម្ម ប្តូរចាស់យកថ្មី (Trade-In)</strong>៖<br>• វាយតម្លៃទូរស័ព្ទចាស់បានតម្លៃខ្ពស់សមរម្យ<br>• ថែមប្រាក់តិចតួចយកស៊េរីថ្មីភ្លាមៗ<br>👉 សូមផ្ញើ <strong>ម៉ូឌែលទូរស័ព្ទចាស់ + ស្ថានភាព (ស្អាត/ឆ្កូត)</strong> មកកាន់ទីនេះ ឬទាក់ទងមក Admin ដើម្បីវាយតម្លៃភ្លាមៗបាទ/ចាស! 📱✨', null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='chat_quick_tradein_q',
            field=models.CharField(blank=True, default='🔄 សួរអំពីការប្តូរចាស់យកថ្មី (Trade-In)?', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='enable_auto_reply',
            field=models.BooleanField(default=False),
        ),
    ]
