# Generated by Django 6.0.2 on 2026-06-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_address_1_order_address_2_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
