# Generated by Django 6.0.2 on 2026-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='មូលហេតុបដិសេធ'),
        ),
    ]
