# Generated by Django 6.0.2 on 2026-09-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'COD'), ('khqr', 'KHQR'), ('online', 'KHQR')], max_length=20),
        ),
    ]
